SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
         HR.EMPLOYEES
    INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
WHERE
    DEPARTMENT_NAME LIKE '%ing';