SELECT
    LAST_NAME,
    DEPARTMENT_NAME,
    SALARY,
    ( SALARY + ( SALARY * 0.05 ) ) AS "New Salary"
FROM
         HR.EMPLOYEES
    INNER JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
WHERE
    DEPARTMENT_NAME LIKE 'Sales'
    OR DEPARTMENT_NAME LIKE 'Shipping';