SELECT
    TO_CHAR(HIRE_DATE, 'YYYY')  AS "Year",
    TO_CHAR(HIRE_DATE, 'Month') AS "Month",
    TO_CHAR(HIRE_DATE, 'DD')    AS "Day",
    FIRST_NAME,
    LAST_NAME
FROM
    HR.EMPLOYEES
WHERE
    TO_CHAR(HIRE_DATE, 'MM') IN ( 10, 11, 12 )
ORDER BY
    TO_CHAR(HIRE_DATE, 'Month') DESC,
    TO_CHAR(HIRE_DATE, 'YYYY') ASC,
    TO_CHAR(HIRE_DATE, 'DD') DESC,
    FIRST_NAME ASC;