SELECT
    LAST_NAME,
    JOB_ID,
    SALARY,
    DEPARTMENT_ID
FROM
    HR.EMPLOYEES
WHERE
    JOB_ID LIKE 'IT_PROG'
    OR ( JOB_ID LIKE 'FI_ACCOUNT'
         AND 5000 <= SALARY
         AND SALARY <= 10000 )
    OR ( DEPARTMENT_ID = 80
         AND 5000 <= SALARY
         AND SALARY <= 10000 )
ORDER BY
    JOB_ID ASC,
    SALARY DESC;