-- practice01
SELECT
    LAST_NAME,
    JOB_ID,
    SALARY,
    DEPARTMENT_ID
FROM
    HR.EMPLOYEES
WHERE
    JOB_ID LIKE 'IT_PROG'
    OR ( JOB_ID LIKE 'FI_ACCOUNT'
         AND 5000 <= SALARY
         AND SALARY <= 10000 )
    OR ( DEPARTMENT_ID = 80
         AND 5000 <= SALARY
         AND SALARY <= 10000 )
ORDER BY
    JOB_ID ASC,
    SALARY DESC;



-- practice02
SELECT
    LENGTH(CONCAT('&firstname', '&lastname')) AS "Length of Name"
FROM
    DUAL;



-- practice03
SELECT
    LAST_NAME,
    DEPARTMENT_NAME,
    SALARY,
    ( SALARY + ( SALARY * 0.05 ) ) AS "New Salary"
FROM
         HR.EMPLOYEES
    INNER JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
WHERE
    DEPARTMENT_NAME LIKE 'Sales'
    OR DEPARTMENT_NAME LIKE 'Shipping';



-- practice04
SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
         HR.EMPLOYEES
    INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
WHERE
    DEPARTMENT_NAME LIKE '%ing';



-- practice05
SELECT
    TO_CHAR(HIRE_DATE, 'YYYY')  AS "Year",
    TO_CHAR(HIRE_DATE, 'Month') AS "Month",
    TO_CHAR(HIRE_DATE, 'DD')    AS "Day",
    FIRST_NAME,
    LAST_NAME
FROM
    HR.EMPLOYEES
WHERE
    TO_CHAR(HIRE_DATE, 'MM') IN ( 10, 11, 12 )
ORDER BY
    TO_CHAR(HIRE_DATE, 'Month') DESC,
    TO_CHAR(HIRE_DATE, 'YYYY') ASC,
    TO_CHAR(HIRE_DATE, 'DD') DESC,
    FIRST_NAME ASC;



-- practice06
SELECT
    TO_CHAR(HIRE_DATE, 'YYYY')  AS "Year",
    TO_CHAR(HIRE_DATE, 'Month') AS "Month",
    TO_CHAR(HIRE_DATE, 'DD')    AS "Day",
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
         HR.EMPLOYEES
    INNER JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
WHERE
    TO_CHAR(HIRE_DATE, 'MM') IN ( 10, 11, 12 )
ORDER BY
    TO_CHAR(HIRE_DATE, 'Month') DESC,
    TO_CHAR(HIRE_DATE, 'YYYY') ASC,
    TO_CHAR(HIRE_DATE, 'DD') DESC,
    FIRST_NAME ASC;